# .github/auto_assign.yml

# Enable adding reviewers to pull requests
addReviewers: true

# Define rules for assigning reviewers based on labels
reviewers:
  - labels:
      - 'ci'
      - 'python'
      - 'tests'
      - 'documentation'
    reviewers:
      - 'lfgranja'
    numberOfReviewers: 1
