# .github/auto_assign.yml

# Enable adding reviewers to pull requests
addReviewers: true

# Enable the use of review groups
useReviewGroups: true

# Define review groups based on labels
reviewGroups:
  ci:
    - 'lfgranja'
  python:
    - 'lfgranja'
  tests:
    - 'lfgranja'
  documentation:
    - 'lfgranja'