# .github/auto_assign.yml

# Enable adding reviewers to pull requests
addReviewers: true

# Configuration for assigning reviewers based on labels.
reviewers:
  - labels:
      - 'ci'
    reviewers:
      - 'lfgranja'
    numberOfReviewers: 1

  - labels:
      - 'python'
    reviewers:
      - 'lfgranja'
    numberOfReviewers: 1

  - labels:
      - 'tests'
    reviewers:
      - 'lfgranja'
    numberOfReviewers: 1

  - labels:
      - 'documentation'
    reviewers:
      - 'lfgranja'
    numberOfReviewers: 1
