name: Post-Push Documentation Generation

on:
  push:
    branches: [dev, main, feature/**, bugfix/**]

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Fetch all history for proper diff analysis
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython openai
        
    - name: Get changed files
      id: changed-files
      run: |
        # Get the list of files changed in this push
        if [ "$GITHUB_EVENT_NAME" = "push" ]; then
          # For push events, compare with the previous commit
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        else
          # For pull request events, use the GitHub API
          CHANGED_FILES=$(jq -r '.pull_request.changed_files[] | .filename' $GITHUB_EVENT_PATH)
        fi
        
        echo "changed_files<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # Save to a file for later use
        echo "$CHANGED_FILES" > changed_files.txt
        
    - name: Generate documentation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: ${{ github.ref_name }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        # Determine the documentation directory name
        if [ -n "$PR_NUMBER" ]; then
          DOC_DIR="devDOCS/$PR_NUMBER"
        else
          DOC_DIR="devDOCS/$BRANCH_NAME"
        fi
        
        # Create the documentation directory
        mkdir -p $DOC_DIR
        
        # Run the documentation generation script (placeholder)
        python devDOCS/generate_docs.py \
          --changed-files changed_files.txt \
          --output-dir $DOC_DIR \
          --branch $BRANCH_NAME \
          --pr-number $PR_NUMBER
          
    - name: Validate documentation
      run: |
        # Check that the required documentation files were created
        DOC_DIR="devDOCS/$PR_NUMBER"
        if [ -n "$PR_NUMBER" ]; then
          REQUIRED_FILES=(
            "LESSONS_LEARNED${PR_NUMBER}.md"
            "FUTURE_WORK_TODO${PR_NUMBER}.md"
            "ISSUES_TO_CREATE${PR_NUMBER}.md"
          )
          
          MISSING_FILES=()
          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$DOC_DIR/$file" ]; then
              MISSING_FILES+=($file)
            fi
          done
          
          if [ ${#MISSING_FILES[@]} -ne 0 ]; then
            echo "Error: Missing required documentation files: ${MISSING_FILES[*]}"
            exit 1
          fi
        fi
        
    - name: Commit and push documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add the generated documentation
        git add devDOCS/
        
        # Check if there are changes to commit
        if ! git diff --staged --quiet; then
          git commit -m "docs: auto-generate development documentation for ${{ github.ref_name }}"
          git push
        else
          echo "No changes to documentation, skipping commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Comment on PR with documentation links
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = ${{ github.event.pull_request.number }};
          const branchName = '${{ github.ref_name }}';
          
          // Create comment with links to generated documentation
          const comment = `## Development Documentation\n\n` +
                         `The following development documentation has been automatically generated:\n\n` +
                         `- [Lessons Learned](https://github.com/${context.repo.owner}/${context.repo.repo}/tree/dev/devDOCS/${branchName}/LESSONS_LEARNED${prNumber}.md)\n` +
                         `- [Future Work](https://github.com/${context.repo.owner}/${context.repo.repo}/tree/dev/devDOCS/${branchName}/FUTURE_WORK_TODO${prNumber}.md)\n` +
                         `- [Issues to Create](https://github.com/${context.repo.owner}/${context.repo.repo}/tree/dev/devDOCS/${branchName}/ISSUES_TO_CREATE${prNumber}.md)\n\n` +
                         `Please review and update as needed.`;
                         
          github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });