name: Lint GitHub Actions Workflows

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # Pinned to v4.1.1
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          actionlint_flags: "-color -verbose"
          fail_level: error
