# .github/workflows/auto-assign.yml
name: 'Auto Assign Reviewers'

on:
  pull_request_target:
    types: [labeled]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_assign.yml'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
