name: Code Quality and Security

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
    
    - name: Set up Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c
      with:
        python-version: '3.10'
    
    - name: Cache Python dependencies
      uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f
      with:
        path: |
          ~/.cache/pip
          ${{ env.pythonLocation }}/lib/python*/site-packages
        key: ${{ runner.os }}-python-3.10-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-3.10-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 bandit
    
    - name: Run Flake8
      run: |
        # Run flake8 for code style checking
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || true
    
    - name: Run Bandit
      run: |
        # Run bandit for security scanning
        bandit -r AGENTIC/ -x AGENTIC/devDOCS/__pycache__/ || true
        bandit -r tests/ || true
    
    - name: Check for common issues
      run: |
        # Check for debug prints
        ! grep -r "print(" --include="*.py" AGENTIC/ tests/ || echo "Warning: Found print statements in code"
        
        # Check for TODO comments
        grep -r "TODO" --include="*.py" --include="*.md" . || echo "No TODO comments found"
        
        # Check for FIXME comments
        grep -r "FIXME" --include="*.py" --include="*.md" . || echo "No FIXME comments found"

  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
    
    - name: Set up Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c
      with:
        python-version: '3.10'
    
    - name: Cache Python dependencies
      uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f
      with:
        path: |
          ~/.cache/pip
          ${{ env.pythonLocation }}/lib/python*/site-packages
        key: ${{ runner.os }}-python-3.10-pip-safety-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-3.10-pip-safety-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety
    
    - name: Check for insecure dependencies
      run: |
        # Check for known security vulnerabilities in dependencies
        if [ -f requirements.txt ]; then
          safety check -r requirements.txt || echo "Warning: Security vulnerabilities found in dependencies"
        fi