name: PR Reviewer Assigner

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: Assign reviewers based on files changed
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr = context.payload.pull_request;
          
          // Get list of files changed in the PR
          const files = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr.number
          });
          
          const reviewers = new Set();
          
          // Assign reviewers based on file paths
          for (const file of files.data) {
            if (file.filename.startsWith('AGENTIC/devDOCS/')) {
              // Assign documentation maintainers
              reviewers.add('lfgranja'); // Replace with actual maintainer usernames
            } else if (file.filename.endsWith('.py')) {
              // Assign Python code reviewers
              reviewers.add('lfgranja'); // Replace with actual maintainer usernames
            } else if (file.filename.endsWith('.md')) {
              // Assign documentation reviewers
              reviewers.add('lfgranja'); // Replace with actual maintainer usernames
            }
          }
          
          // Assign reviewers if any were identified
          if (reviewers.size > 0) {
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              reviewers: Array.from(reviewers)
            });
          }