name: PR Labeler and Reviewer Assigner

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label-and-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Assign reviewers
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(label => label.name);
            const config = {
              'ci': ['lfgranja'],
              'python': ['lfgranja'],
              'tests': ['lfgranja'],
              'documentation': ['lfgranja']
            };
            const reviewers = new Set();
            for (const label of labels) {
              if (config[label]) {
                config[label].forEach(reviewer => reviewers.add(reviewer));
              }
            }
            if (reviewers.size > 0) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                reviewers: Array.from(reviewers)
              });
            }
